#!/bin/bash
backup="$@"
[ ! -e "${backup%backup}" ] && [ -e "${backup}"  ] && mv "${backup}" "${backup%backup}" && exit 0
[ $(stat -c '%s' "${backup}" "${backup%backup}" | sort -u | wc -l) -eq 1 ] && echo "backup size matches for ${backup%backup}, updating timestamps" && touch --date=@$(stat -c '%Y' "${backup}" "${backup%backup}" | sort -n | head -n1) "${backup}" "${backup%backup}" && [ $(sha512sum "${backup}" "${backup%backup}" | cut -d ' ' -f1 | sort -u | wc -l) -eq 1 ] && echo "sha512sum matches for ${backup%backup}, removing backup" && rm -v "${backup}"
