#!/bin/bash
backup="$@"
original="${backup%.backup}"
if [ ! -e "${original}" ] && [ -e "${backup}"  ]; then
    mv -v "${backup}" "${original}"
    exit 0
fi

if [ $(stat -c '%s' "${backup}" "${original}" | sort -u | wc -l) -eq 1 ]; then
    echo "backup size matches for ${original}, updating timestamps"
    touch --date=@$(stat -c '%Y' "${backup}" "${original}" | sort -n | head -n1) "${backup}" "${original}"
    if [ $(sha512sum "${backup}" "${original}" | cut -d ' ' -f1 | sort -u | wc -l) -eq 1 ];then
        echo "sha512sum matches for ${original}, removing backup"
        rm -v "${backup}"
    fi
fi
